feat : _app Box
codestates-seb/seb43_main_032 pull request #28
Opened 2023-05-06 13:47 UTC by shdomi8599

- Header 컴포넌트로 인해 Main padding-top을 추가하였습니다.

2023-05-06 16:15 UTC, Latemarch requested changes

2023-05-06 16:15 UTC, Latemarch commented on frontend/pages/_app.tsx
> +  padding-top: 100px;
```suggestion
  padding-top: 80px;
```
Header  스타일의 height가 80px이라 맞춰주는 것이 좋을 것 같습니다.

2023-05-06 18:26 UTC, shdomi8599 commented on frontend/pages/_app.tsx
> +  padding-top: 100px;
수정하였습니다~

2023-05-07 09:09 UTC, choigirang approved these changes

2023-05-07 09:53 UTC, merged